version: "3"
services:
  calculatorclient:
    build: ./calculatorClient
    container_name: calculatorclient
    ports:
      - "8080:80"
    depends_on:
      - calculatorappserver
      - calculatorwebserver

  calculatorwebserver:
    build: ./calculatorWebServer
    container_name: calculatorwebserver
    depends_on:
      - calculatorappserver

  calculatorappserver:

    build:
      context: .
      dockerfile: calculatorService/Dockerfile
    container_name: calculatorappserver
    entrypoint: ['uwsgi', 'app_uwsgi.ini']
